name: Format Go code

on:
  pull_request:
    branches:
      - "master"
      - "develop"

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        set-safe-directory: /github/workspace

    - name: Golang Formatter
      uses: sladyn98/auto-go-format@v0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
