name: Format Go code

on:
  pull_request:
    branches:
      - "master"
      - "develop"

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        set-safe-directory: /github/workspace
    - name: Fix git safe.directory in container  # https://github.com/actions/runner/issues/2033
      run: mkdir -p /home/runner/work/_temp/_github_home && printf "[safe]\n\tdirectory = /github/workspace" > /home/runner/work/_temp/_github_home/.gitconfig

    - name: Format code
      uses: iamnotaturtle/auto-gofmt@v2.1.0
